"""
bringup.launch.py — Full stack on real hardware (Toradex + Mallow carrier).

Hardware prerequisites:
  1. CAN bus configured: ip link set can0 type can bitrate 1000000 && ip link set can0 up
     (systemd service can0.service handles this at boot — see docs/DEPLOYMENT.md)
  2. SICK TIM571 reachable on Ethernet (default IP: 192.168.0.1)
  3. Camera at /dev/video0
  4. All 5 CAN nodes powered and operational

Launch order (dependency chain):
  canopen_container → sick_scan_xd, usb_cam → lidar_safety → motion_coordinator
  → turntable_monitor → led_controller → state_machine

ros2_canopen notes:
  The canopen_master_driver and proxy drivers run inside a ComposableNodeContainer
  so they share a single process and the bus lifecycle (NMT boot, SYNC, PDO) is
  managed as a unit.

  Plugin names for ros-humble-canopen-* apt packages:
    ros2_canopen::MasterDriver    (canopen_master_driver)
    ros2_canopen::ProxyDriver     (canopen_proxy_driver)

  If launch fails with "Failed to find class", verify with:
    ros2 component types canopen_master_driver
    ros2 component types canopen_proxy_driver

  For vcan0 testing on Windows dev (no Toradex needed):
    modprobe vcan && ip link add dev vcan0 type vcan && ip link set vcan0 up
    ros2 launch vinyl_robot bringup.launch.py can_interface:=vcan0
"""

import os

from ament_index_python.packages import get_package_share_directory
from launch import LaunchDescription
from launch.actions import DeclareLaunchArgument, IncludeLaunchDescription
from launch.conditions import IfCondition
from launch.launch_description_sources import PythonLaunchDescriptionSource
from launch.substitutions import LaunchConfiguration
from launch_ros.actions import ComposableNodeContainer, Node
from launch_ros.descriptions import ComposableNode


def generate_launch_description():
    config_dir = os.path.join(get_package_share_directory("vinyl_robot"), "config")
    config_file = os.path.join(config_dir, "robot_params.yaml")
    bus_config = os.path.join(config_dir, "bus.yml")

    can_interface_arg = DeclareLaunchArgument(
        "can_interface", default_value="can0",
        description="SocketCAN interface name (can0 for hardware, vcan0 for dev testing)"
    )
    lidar_ip_arg = DeclareLaunchArgument(
        "lidar_ip", default_value="192.168.0.1", description="IP address of the SICK TIM571 LiDAR"
    )
    web_ui_arg = DeclareLaunchArgument(
        "web_ui", default_value="true", description="Launch rosbridge + web UI (true/false)"
    )

    # ── CANopen master + proxy drivers (component container) ──────────────────
    # All five proxy drivers are loaded alongside the master in one container.
    # bus.yml (generated by CMake configure_file) has EDS paths already resolved.
    canopen_container = ComposableNodeContainer(
        name="canopen_container",
        namespace="",
        package="rclcpp_components",
        executable="component_container",
        composable_node_descriptions=[
            ComposableNode(
                package="canopen_master_driver",
                plugin="ros2_canopen::MasterDriver",
                name="canopen_master",
                parameters=[{
                    "bus_config": bus_config,
                    "can_interface_name": LaunchConfiguration("can_interface"),
                }],
            ),
            ComposableNode(
                package="canopen_proxy_driver",
                plugin="ros2_canopen::ProxyDriver",
                name="x_axis",
            ),
            ComposableNode(
                package="canopen_proxy_driver",
                plugin="ros2_canopen::ProxyDriver",
                name="z_axis",
            ),
            ComposableNode(
                package="canopen_proxy_driver",
                plugin="ros2_canopen::ProxyDriver",
                name="a_axis",
            ),
            ComposableNode(
                package="canopen_proxy_driver",
                plugin="ros2_canopen::ProxyDriver",
                name="pincher",
            ),
            ComposableNode(
                package="canopen_proxy_driver",
                plugin="ros2_canopen::ProxyDriver",
                name="player",
            ),
        ],
        output="screen",
    )

    # ── SICK TIM571 LiDAR ─────────────────────────────────────────────────────
    sick_scan = Node(
        package="sick_scan_xd",
        executable="sick_generic_caller",
        name="sick_scan_xd",
        parameters=[
            {
                "scanner_type": "sick_tim_5xx",
                "hostname": LaunchConfiguration("lidar_ip"),
                "port": "2112",
                "frame_id": "laser",
            }
        ],
        output="screen",
    )

    # ── USB camera ────────────────────────────────────────────────────────────
    usb_cam = Node(
        package="usb_cam",
        executable="usb_cam_node_exe",
        name="usb_cam",
        parameters=[
            {
                "video_device": "/dev/video0",
                "image_width": 640,
                "image_height": 480,
                "framerate": 15.0,
                "pixel_format": "yuyv",
            }
        ],
        output="screen",
        remappings=[("image_raw", "/camera/image_raw")],
    )

    # ── LiDAR safety (real mode) ──────────────────────────────────────────────
    lidar_safety = Node(
        package="lidar_safety",
        executable="lidar_safety",
        name="lidar_safety",
        parameters=[
            {
                "mock_mode": False,
                "warning_radius_mm": 400.0,
                "stop_radius_mm": 200.0,
            }
        ],
        output="screen",
    )

    # ── CANopen bridge (ProxyDriver COData ↔ UInt8MultiArray PDOs) ───────────
    canopen_bridge = Node(
        package="canopen_bridge",
        executable="canopen_bridge",
        name="canopen_bridge",
        output="screen",
    )

    # ── Motion coordinator ────────────────────────────────────────────────────
    motion_coordinator = Node(
        package="motion_coordinator",
        executable="motion_coordinator",
        name="motion_coordinator",
        parameters=[{"config_path": config_file}],
        output="screen",
    )

    # ── Turntable monitor (real camera) ───────────────────────────────────────
    turntable_monitor = Node(
        package="turntable_monitor",
        executable="turntable_monitor",
        name="turntable_monitor",
        parameters=[{"mock_mode": False}],
        output="screen",
    )

    # ── LED controller ────────────────────────────────────────────────────────
    led_controller = Node(
        package="led_controller",
        executable="led_controller",
        name="led_controller",
        output="screen",
    )

    # ── State machine ─────────────────────────────────────────────────────────
    state_machine = Node(
        package="state_machine",
        executable="state_machine",
        name="state_machine",
        output="screen",
    )

    # ── Diagnostics ───────────────────────────────────────────────────────────
    diagnostics = Node(
        package="diagnostics_aggregator",
        executable="diagnostics_aggregator",
        name="diagnostics_aggregator",
        output="screen",
    )

    # ── Web UI ────────────────────────────────────────────────────────────────
    web_ui = IncludeLaunchDescription(
        PythonLaunchDescriptionSource(
            os.path.join(
                get_package_share_directory("web_interface"), "launch", "web_ui.launch.py"
            )
        ),
        condition=IfCondition(LaunchConfiguration("web_ui")),
    )

    return LaunchDescription(
        [
            can_interface_arg,
            lidar_ip_arg,
            web_ui_arg,
            canopen_container,
            canopen_bridge,
            sick_scan,
            usb_cam,
            lidar_safety,
            motion_coordinator,
            turntable_monitor,
            led_controller,
            state_machine,
            diagnostics,
            web_ui,
        ]
    )
